import React, { createContext, useContext, useState, ReactNode } from 'react';

interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const languages: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
];

const translations = {
  en: {
    'language.title': 'Choose Your Language',
    'language.subtitle': 'Select your preferred language',
    'profile.title': 'Create Your Health Profile',
    'profile.name': 'Full Name',
    'profile.name.placeholder': 'Enter your full name',
    'profile.age': 'Age',
    'profile.age.placeholder': 'Enter your age',
    'profile.gender': 'Gender',
    'profile.gender.male': 'Male',
    'profile.gender.female': 'Female',
    'profile.gender.other': 'Other',
    'profile.health.conditions': 'Health Conditions (Select all that apply)',
    'profile.continue': 'Continue to Dashboard',
    'dashboard.welcome': 'Welcome back',
    'dashboard.today.medicines': 'Medicines Today',
    'dashboard.active.days': 'Active Days',
    'dashboard.reports.uploaded': 'Reports Uploaded',
    'dashboard.compliance.rate': 'Compliance Rate',
    'dashboard.scan.prescription': 'Scan Prescription',
    'dashboard.scan.description': 'Upload or scan prescription for analysis',
    'dashboard.voice.assistant': 'Voice Assistant',
    'dashboard.voice.description': 'Ask health questions with voice',
    'dashboard.wellness.tips': 'Wellness Tips',
    'dashboard.wellness.description': 'Get personalized health recommendations',
    'dashboard.my.medicines': 'My Medicines',
    'dashboard.medicines.description': 'View and manage your medications',
    'dashboard.reminders': 'Medicine Reminders',
    'dashboard.reminders.description': 'Set and manage medication alerts',
    'dashboard.progress': 'Health Progress',
    'dashboard.progress.description': 'Track your health journey',
    'voice.title': 'Voice Assistant',
    'voice.subtitle': 'Tap the microphone and ask your health questions',
    'voice.listening': 'Listening... Ask me anything!',
    'voice.back': '← Back to Dashboard',
    'voice.safety.disclaimer': 'This is general guidance; consult your doctor.',
    'voice.suggestions.title': 'Suggested Actions',
    'voice.action.add.reminder': 'Add to reminder',
    'voice.action.add.groceries': 'Add to grocery list',
    'voice.action.schedule.appointment': 'Schedule appointment',
    'voice.action.view.reports': 'View health reports',
    'wellness.title': 'Wellness Tips',
    'wellness.back': '← Back to Dashboard',
    'coming.soon': 'This feature is coming soon!',
    'health.conditions.diabetes': 'Diabetes',
    'health.conditions.hypertension': 'High Blood Pressure',
    'health.conditions.heart': 'Heart Disease',
    'health.conditions.arthritis': 'Arthritis',
    'health.conditions.cholesterol': 'High Cholesterol',
    'health.conditions.thyroid': 'Thyroid',
    'health.conditions.kidney': 'Kidney Disease',
    'health.conditions.asthma': 'Asthma',
  },
  hi: {
    'language.title': 'अपनी भाषा चुनें',
    'language.subtitle': 'अपनी पसंदीदा भाषा चुनें',
    'profile.title': 'अपना स्वास्थ्य प्रोफ़ाइल बनाएं',
    'profile.name': 'पूरा नाम',
    'profile.name.placeholder': 'अपना पूरा नाम दर्ज करें',
    'profile.age': 'उम्र',
    'profile.age.placeholder': 'अपनी उम्र दर्ज करें',
    'profile.gender': 'लिंग',
    'profile.gender.male': 'पुरुष',
    'profile.gender.female': 'महिला',
    'profile.gender.other': 'अन्य',
    'profile.health.conditions': 'स्वास्थ्य स्थितियां (सभी लागू का चयन करें)',
    'profile.continue': 'डैशबोर्ड पर जाएं',
    'dashboard.welcome': 'वापस स्वागत है',
    'dashboard.today.medicines': 'आज की दवाएं',
    'dashboard.active.days': 'सक्रिय दिन',
    'dashboard.reports.uploaded': 'अपलोड की गई रिपोर्ट',
    'dashboard.compliance.rate': 'अनुपालन दर',
    'dashboard.scan.prescription': 'प्रिस्क्रिप्शन स्कैन करें',
    'dashboard.scan.description': 'विश्लेषण के लिए प्रिस्क्रिप्शन अपलोड या स्कैन करें',
    'dashboard.voice.assistant': 'वॉइस असिस्टेंट',
    'dashboard.voice.description': 'आवाज से स्वास्थ्य सवाल पूछें',
    'dashboard.wellness.tips': 'कल्याण सुझाव',
    'dashboard.wellness.description': 'व्यक्तिगत स्वास्थ्य सिफारिशें प्राप्त करें',
    'dashboard.my.medicines': 'मेरी दवाएं',
    'dashboard.medicines.description': 'अपनी दवाओं को देखें और प्रबंधित करें',
    'dashboard.reminders': 'दवा रिमाइंडर',
    'dashboard.reminders.description': 'दवा अलर्ट सेट और प्रबंधित करें',
    'dashboard.progress': 'स्वास्थ्य प्रगति',
    'dashboard.progress.description': 'अपनी स्वास्थ्य यात्रा को ट्रैक करें',
    'voice.title': 'वॉइस असिस्टेंट',
    'voice.subtitle': 'माइक्रोफोन पर टैप करें और अपने स्वास्थ्य प्रश्न पूछें',
    'voice.listening': 'सुन रहा हूं... मुझसे कुछ भी पूछें!',
    'voice.back': '← डैशबोर्ड पर वापस',
    'voice.safety.disclaimer': 'यह सामान्य मार्गदर्शन है; अपने डॉक्टर से सलाह लें।',
    'voice.suggestions.title': 'सुझाए गए कार्य',
    'voice.action.add.reminder': 'रिमाइंडर में जोड़ें',
    'voice.action.add.groceries': 'किराने की सूची में जोड़ें',
    'voice.action.schedule.appointment': 'अपॉइंटमेंट शेड्यूल करें',
    'voice.action.view.reports': 'स्वास्थ्य रिपोर्ट देखें',
    'wellness.title': 'कल्याण सुझाव',
    'wellness.back': '← डैशबोर्ड पर वापस',
    'coming.soon': 'यह सुविधा जल्द आ रही है!',
    'health.conditions.diabetes': 'मधुमेह',
    'health.conditions.hypertension': 'उच्च रक्तचाप',
    'health.conditions.heart': 'हृदय रोग',
    'health.conditions.arthritis': 'गठिया',
    'health.conditions.cholesterol': 'उच्च कोलेस्ट्रॉल',
    'health.conditions.thyroid': 'थायराइड',
    'health.conditions.kidney': 'गुर्दे की बीमारी',
    'health.conditions.asthma': 'दमा',
  },
  kn: {
    'language.title': 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'language.subtitle': 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'profile.title': 'ನಿಮ್ಮ ಆರೋಗ್ಯ ಪ್ರೊಫೈಲ್ ರಚಿಸಿ',
    'profile.name': 'ಪೂರ್ಣ ಹೆಸರು',
    'profile.name.placeholder': 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
    'profile.age': 'ವಯಸ್ಸು',
    'profile.age.placeholder': 'ನಿಮ್ಮ ವಯಸ್ಸನ್ನು ನಮೂದಿಸಿ',
    'profile.gender': 'ಲಿಂಗ',
    'profile.gender.male': 'ಪುರುಷ',
    'profile.gender.female': 'ಮಹಿಳೆ',
    'profile.gender.other': 'ಇತರ',
    'profile.health.conditions': 'ಆರೋಗ್ಯ ಸ್ಥಿತಿಗಳು (ಅನ್ವಯಿಸುವ ಎಲ್ಲವನ್ನೂ ಆಯ್ಕೆಮಾಡಿ)',
    'profile.continue': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಮುಂದುವರಿಯಿರಿ',
    'dashboard.welcome': 'ಮರಳಿ ಸ್ವಾಗತ',
    'dashboard.today.medicines': 'ಇಂದಿನ ಔಷಧಿಗಳು',
    'dashboard.active.days': 'ಸಕ್ರಿಯ ದಿನಗಳು',
    'dashboard.reports.uploaded': 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ವರದಿಗಳು',
    'dashboard.compliance.rate': 'ಅನುಸರಣೆ ದರ',
    'dashboard.scan.prescription': 'ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    'dashboard.scan.description': 'ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಅಪ್‌ಲೋಡ್ ಅಥವಾ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    'dashboard.voice.assistant': 'ಧ್ವನಿ ಸಹಾಯಕ',
    'dashboard.voice.description': 'ಧ್ವನಿಯೊಂದಿಗೆ ಆರೋಗ್ಯ ಪ್ರಶ್ನೆಗಳನ್ನು ಕೇಳಿ',
    'dashboard.wellness.tips': 'ಕ್ಷೇಮ ಸಲಹೆಗಳು',
    'dashboard.wellness.description': 'ವೈಯಕ್ತಿಕ ಆರೋಗ್ಯ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ',
    'dashboard.my.medicines': 'ನನ್ನ ಔಷಧಿಗಳು',
    'dashboard.medicines.description': 'ನಿಮ್ಮ ಔಷಧಿಗಳನ್ನು ವೀಕ್ಷಿಸಿ ಮತ್ತು ನಿರ್ವಹಿಸಿ',
    'dashboard.reminders': 'ಔಷಧಿ ರಿಮೈಂಡರ್‌ಗಳು',
    'dashboard.reminders.description': 'ಔಷಧಿ ಎಚ್ಚರಿಕೆಗಳನ್ನು ಹೊಂದಿಸಿ ಮತ್ತು ನಿರ್ವಹಿಸಿ',
    'dashboard.progress': 'ಆರೋಗ್ಯ ಪ್ರಗತಿ',
    'dashboard.progress.description': 'ನಿಮ್ಮ ಆರೋಗ್ಯ ಪ್ರಯಾಣವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    'voice.title': 'ಧ್ವನಿ ಸಹಾಯಕ',
    'voice.subtitle': 'ಮೈಕ್ರೊಫೋನ್ ಟ್ಯಾಪ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಆರೋಗ್ಯ ಪ್ರಶ್ನೆಗಳನ್ನು ಕೇಳಿ',
    'voice.listening': 'ಕೇಳುತ್ತಿದ್ದೇನೆ... ನನಗೆ ಏನನ್ನಾದರೂ ಕೇಳಿ!',
    'voice.back': '← ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂತಿರುಗಿ',
    'wellness.title': 'ಕ್ಷೇಮ ಸಲಹೆಗಳು',
    'wellness.back': '← ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂತಿರುಗಿ',
    'coming.soon': 'ಈ ವೈಶಿಷ್ಟ್ಯ ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ!',
    'health.conditions.diabetes': 'ಮಧುಮೇಹ',
    'health.conditions.hypertension': 'ಅಧಿಕ ರಕ್ತದೊತ್ತಡ',
    'health.conditions.heart': 'ಹೃದಯ ಕಾಯಿಲೆ',
    'health.conditions.arthritis': 'ಸಂಧಿವಾತ',
    'health.conditions.cholesterol': 'ಅಧಿಕ ಕೊಲೆಸ್ಟ್ರಾಲ್',
    'health.conditions.thyroid': 'ಥೈರಾಯ್ಡ್',
    'health.conditions.kidney': 'ಮೂತ್ರಪಿಂಡ ಕಾಯಿಲೆ',
    'health.conditions.asthma': 'ಆಸ್ತಮಾ',
  },
  ta: {
    'language.title': 'உங்கள் மொழியைத் தேர்ந்தெடுங்கள்',
    'language.subtitle': 'உங்களுக்கு விருப்பமான மொழியைத் தேர்ந்தெடுங்கள்',
    'profile.title': 'உங்கள் ஆரோக்கிய விவரத்தை உருவாக்கவும்',
    'profile.name': 'முழு பெயர்',
    'profile.name.placeholder': 'உங்கள் முழு பெயரை உள்ளிடவும்',
    'profile.age': 'வயது',
    'profile.age.placeholder': 'உங்கள் வயதை உள்ளிடவும்',
    'profile.gender': 'பாலினம்',
    'profile.gender.male': 'ஆண்',
    'profile.gender.female': 'பெண்',
    'profile.gender.other': 'மற்றவை',
    'profile.health.conditions': 'உடல்நலநிலைகள் (பொருந்தும் அனைத்தையும் தேர்ந்தெடுக்கவும்)',
    'profile.continue': 'டாஷ்போர்டுக்கு தொடரவும்',
    'dashboard.welcome': 'மீண்டும் வரவேற்கிறோம்',
    'dashboard.today.medicines': 'இன்றைய மருந்துகள்',
    'dashboard.active.days': 'செயல்படும் நாட்கள்',
    'dashboard.reports.uploaded': 'பதிவேற்றப்பட்ட அறிக்கைகள்',
    'dashboard.compliance.rate': 'இணக்க விகிதம்',
    'dashboard.scan.prescription': 'மருந்துச் சீட்டை ஸ்கேன் செய்யவும்',
    'dashboard.scan.description': 'பகுப்பாய்வுக்காக மருந்துச் சீட்டை பதிவேற்றவும் அல்லது ஸ்கேன் செய்யவும்',
    'dashboard.voice.assistant': 'குரல் உதவியாளர்',
    'dashboard.voice.description': 'குரல் மூலம் உடல்நலம் பற்றிய கேள்விகளைக் கேளுங்கள்',
    'dashboard.wellness.tips': 'நல்வாழ்வு குறிப்புகள்',
    'dashboard.wellness.description': 'தனிப்பயனாக்கப்பட்ட உடல்நல பரிந்துரைகளைப் பெறுங்கள்',
    'dashboard.my.medicines': 'என் மருந்துகள்',
    'dashboard.medicines.description': 'உங்கள் மருந்துகளைப் பார்க்கவும் நிர்வகிக்கவும்',
    'dashboard.reminders': 'மருந்து நினைவூட்டல்கள்',
    'dashboard.reminders.description': 'மருந்து எச்சரிக்கைகளை அமைத்து நிர்வகிக்கவும்',
    'dashboard.progress': 'உடல்நல முன்னேற்றம்',
    'dashboard.progress.description': 'உங்கள் உடல்நல பயணத்தைத் தொடரவும்',
    'voice.title': 'குரல் உதவியாளர்',
    'voice.subtitle': 'மைக்ரோஃபோனை அழுத்தி உங்கள் உடல்நல கேள்விகளைக் கேளுங்கள்',
    'voice.listening': 'கேட்டுக்கொண்டிருக்கிறேன்... என்னிடம் எதையும் கேளுங்கள்!',
    'voice.back': '← டாஷ்போர்டுக்கு திரும்பவும்',
    'wellness.title': 'நல்வாழ்வு குறிப்புகள்',
    'wellness.back': '← டாஷ்போர்டுக்கு திரும்பவும்',
    'coming.soon': 'இந்த அம்சம் விரைவில் வருகிறது!',
    'health.conditions.diabetes': 'நீரிழிவு',
    'health.conditions.hypertension': 'உயர் இரத்த அழுத்தம்',
    'health.conditions.heart': 'இதய நோய்',
    'health.conditions.arthritis': 'மூட்டுவலி',
    'health.conditions.cholesterol': 'உயர் கொலஸ்ட்ரால்',
    'health.conditions.thyroid': 'தைராய்டு',
    'health.conditions.kidney': 'சிறுநீரக நோய்',
    'health.conditions.asthma': 'ஆஸ்துமா',
  },
  bn: {
    'language.title': 'আপনার ভাষা নির্বাচন করুন',
    'language.subtitle': 'আপনার পছন্দের ভাষা নির্বাচন করুন',
    'profile.title': 'আপনার স্বাস্থ্য প্রোফাইল তৈরি করুন',
    'profile.name': 'পূর্ণ নাম',
    'profile.name.placeholder': 'আপনার পূর্ণ নাম লিখুন',
    'profile.age': 'বয়স',
    'profile.age.placeholder': 'আপনার বয়স লিখুন',
    'profile.gender': 'লিঙ্গ',
    'profile.gender.male': 'পুরুষ',
    'profile.gender.female': 'মহিলা',
    'profile.gender.other': 'অন্যান্য',
    'profile.health.conditions': 'স্বাস্থ্য অবস্থা (যেগুলি প্রযোজ্য সব নির্বাচন করুন)',
    'profile.continue': 'ড্যাশবোর্ডে চালিয়ে যান',
    'dashboard.welcome': 'আবার স্বাগতম',
    'dashboard.today.medicines': 'আজকের ওষুধ',
    'dashboard.active.days': 'সক্রিয় দিন',
    'dashboard.reports.uploaded': 'আপলোড করা রিপোর্ট',
    'dashboard.compliance.rate': 'অনুসরণের হার',
    'dashboard.scan.prescription': 'প্রেসক্রিপশন স্ক্যান করুন',
    'dashboard.scan.description': 'বিশ্লেষণের জন্য প্রেসক্রিপশন আপলোড বা স্ক্যান করুন',
    'dashboard.voice.assistant': 'ভয়েস সহায়ক',
    'dashboard.voice.description': 'ভয়েসের মাধ্যমে স্বাস্থ্য প্রশ্ন জিজ্ঞাসা করুন',
    'dashboard.wellness.tips': 'সুস্থতার পরামর্শ',
    'dashboard.wellness.description': 'ব্যক্তিগত স্বাস্থ্য সুপারিশ পান',
    'dashboard.my.medicines': 'আমার ওষুধ',
    'dashboard.medicines.description': 'আপনার ওষুধগুলি দেখুন এবং পরিচালনা করুন',
    'dashboard.reminders': 'ওষুধের রিমাইন্ডার',
    'dashboard.reminders.description': 'ওষুধের সতর্কতা সেট এবং পরিচালনা করুন',
    'dashboard.progress': 'স্বাস্থ্য অগ্রগতি',
    'dashboard.progress.description': 'আপনার স্বাস্থ্য যাত্রা ট্র্যাক করুন',
    'voice.title': 'ভয়েস সহায়ক',
    'voice.subtitle': 'মাইক্রোফোনে ট্যাপ করুন এবং আপনার স্বাস্থ্য প্রশ্ন জিজ্ঞাসা করুন',
    'voice.listening': 'শুনছি... আমাকে কিছু জিজ্ঞাসা করুন!',
    'voice.back': '← ড্যাশবোর্ডে ফিরে যান',
    'wellness.title': 'সুস্থতার পরামর্শ',
    'wellness.back': '← ড্যাশবোর্ডে ফিরে যান',
    'coming.soon': 'এই বৈশিষ্ট্য শীঘ্রই আসছে!',
    'health.conditions.diabetes': 'ডায়াবেটিস',
    'health.conditions.hypertension': 'উচ্চ রক্তচাপ',
    'health.conditions.heart': 'হৃদরোগ',
    'health.conditions.arthritis': 'বাত',
    'health.conditions.cholesterol': 'উচ্চ কোলেস্টেরল',
    'health.conditions.thyroid': 'থাইরয়েড',
    'health.conditions.kidney': 'কিডনি রোগ',
    'health.conditions.asthma': 'হাঁপানি',
  },
  te: {
    'language.title': 'మీ భాషను ఎంచుకోండి',
    'language.subtitle': 'మీకు ఇష్టమైన భాషను ఎంచుకోండి',
    'profile.title': 'మీ ఆరోగ్య ప్రొఫైల్‌ను సృష్టించండి',
    'profile.name': 'పూర్తి పేరు',
    'profile.name.placeholder': 'మీ పూర్తి పేరును నమోదు చేయండి',
    'profile.age': 'వయస్సు',
    'profile.age.placeholder': 'మీ వయస్సును నమోదు చేయండి',
    'profile.gender': 'లింగం',
    'profile.gender.male': 'పురుషుడు',
    'profile.gender.female': 'మహిళ',
    'profile.gender.other': 'ఇతర',
    'profile.health.conditions': 'ఆరోగ్య పరిస్థితులు (వర్తించే అన్నింటినీ ఎంచుకోండి)',
    'profile.continue': 'డ్యాష్‌బోర్డ్‌కు కొనసాగండి',
    'dashboard.welcome': 'తిరిగి స్వాగతం',
    'dashboard.today.medicines': 'నేటి మందులు',
    'dashboard.active.days': 'సక్రియ దినాలు',
    'dashboard.reports.uploaded': 'అప్‌లోడ్ చేసిన నివేదికలు',
    'dashboard.compliance.rate': 'అనుగుణ్యత రేటు',
    'dashboard.scan.prescription': 'ప్రిస్క్రిప్షన్ స్కాన్ చేయండి',
    'dashboard.scan.description': 'విశ్లేషణ కోసం ప్రిస్క్రిప్షన్‌ను అప్‌లోడ్ లేదా స్కాన్ చేయండి',
    'dashboard.voice.assistant': 'వాయిస్ అసిస్టెంట్',
    'dashboard.voice.description': 'వాయిస్‌తో ఆరోగ్య ప్రశ్నలు అడగండి',
    'dashboard.wellness.tips': 'సంక్షేమ చిట్కాలు',
    'dashboard.wellness.description': 'వ్యక్తిగత ఆరోగ్య సిఫార్సులను పొందండి',
    'dashboard.my.medicines': 'నా మందులు',
    'dashboard.medicines.description': 'మీ మందులను చూడండి మరియు నిర్వహించండి',
    'dashboard.reminders': 'మందు రిమైండర్‌లు',
    'dashboard.reminders.description': 'మందు హెచ్చరికలను సెట్ చేసి నిర్వహించండి',
    'dashboard.progress': 'ఆరోగ్య పురోగతి',
    'dashboard.progress.description': 'మీ ఆరోగ్య ప్రయాణాన్ని ట్రాక్ చేయండి',
    'voice.title': 'వాయిస్ అసిస్టెంట్',
    'voice.subtitle': 'మైక్రోఫోన్‌పై ట్యాప్ చేసి మీ ఆరోగ్య ప్రశ్నలను అడగండి',
    'voice.listening': 'వింటున్నాను... నన్ను ఏదైనా అడగండి!',
    'voice.back': '← డ్యాష్‌బోర్డ్‌కు తిరిగి',
    'wellness.title': 'సంక్షేమ చిట్కాలు',
    'wellness.back': '← డ్యాష్‌బోర్డ్‌కు తిరిగి',
    'coming.soon': 'ఈ ఫీచర్ త్వరలో వస్తుంది!',
    'health.conditions.diabetes': 'మధుమేహం',
    'health.conditions.hypertension': 'అధిక రక్తపోటు',
    'health.conditions.heart': 'గుండె జబ్బు',
    'health.conditions.arthritis': 'కీళ్లనొప్పులు',
    'health.conditions.cholesterol': 'అధిక కొలెస్ట్రాల్',
    'health.conditions.thyroid': 'థైరాయిడ్',
    'health.conditions.kidney': 'మూత్రపిండాల జబ్బు',
    'health.conditions.asthma': 'అస్థమా',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(languages[0]);

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
  };

  const t = (key: string): string => {
    const languageTranslations = translations[currentLanguage.code as keyof typeof translations];
    return languageTranslations?.[key as keyof typeof languageTranslations] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export { languages, type Language };